services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  postgis:
    image: foundation-postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: foundation