set search_path to foundation, public;

insert into foundation.users (username, password_hash, first_name, last_name)
    VALUES ('stoyan', '$2a$10$SZ.59/WGzU2ZdpKWplJKLeoTkrqp.nfEeJDKx37pYHvuTrZ5Vr8I2', 'Stoyan', 'Malinin'); -- pass: 123456

insert into foundation.searches (title, description, created_at, owner_username)
    VALUES ('Test-1', 'Generated by init.sql', '2022-11-19 03:04:05-06', 'stoyan');

insert into foundation.searches (title, description, created_at, owner_username)
    VALUES ('Test-2', 'Generated by init.sql', '2022-11-19 03:04:05-06', 'stoyan');

DO $$
DECLARE
    i INTEGER;
BEGIN
    FOR i IN 1..100 LOOP
        -- Свиленград, кръготовото до автогарата
        insert into foundation.presences (point, timestamp) values (st_point(26.206344604492188, 41.76790237426758), 0);
    END LOOP;
END $$;

insert into foundation.search_to_presence (search_id, presence_id)
    select searches.id, presences.id FROM (SELECT 1 as id) as searches CROSS JOIN foundation.presences;

insert into foundation.search_to_presence (search_id, presence_id) VALUES (2, 3)