set search_path to foundation, public;

insert into foundation.foundation.searches (title, description) VALUES ('Test', 'Generated by init.sql');

DO $$
DECLARE
    i INTEGER;
BEGIN
    FOR i IN 1..100 LOOP
        -- Свиленград, кръготовото до автогарата
        insert into foundation.foundation.presences (point, timestamp) values (st_point(26.206344604492188, 41.76790237426758), 0);
    END LOOP;
END $$;

insert into foundation.foundation.search_to_presence (search_id, presence_id)
    select searches.id, presences.id FROM foundation.foundation.searches CROSS JOIN foundation.foundation.presences;